services:
  - type: web
    name: elektronkundalik
    env: python
    buildCommand: ""
    startCommand: gunicorn config.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: 3.12
